// If left empty, everything is allowed, otherwise only blacklisted items will be unavailable

blacklist1 =
[	
	// TCGM Bike Backpack
	"TCGM_BikePack_nht",
	"TCGM_BikePack_hexa",
	"TCGM_BikePack_hex",
	"TCGM_BikePack_hexw",
	"TCGM_BikePack_oli",
	"TCGM_BikePack_snd",
	"TCGM_BikePack_win",
	
	// Thong Underwears
	"TCGM_f_Thong_Flowers",
	"TCGM_f_Thong_Hearts",
	"TCGM_f_Thong_Leafs",
	"TCGM_f_Thong_Maya",
	"TCGM_f_Thong_Poker",
	"TCGM_f_Thong_Blk",
	"TCGM_f_Thong_Blue",
	"TCGM_f_Thong_Brown",
	"TCGM_f_Thong_LGreen",
	"TCGM_f_Thong_DGreen",
	"TCGM_f_Thong_Wht",
	"TCGM_f_Thong_WGreen",
	
	// Swimsuits and Mini-Skirts
	"TCGM_F_Mini_IDAP",
	"TCGM_F_Mini_Casual2",
	"TCGM_F_Mini_Casual5",
	"TCGM_F_Mini_Casual3",
	"TCGM_F_Mini_Casual4",
	"TCGM_F_Mini_Navy",
	"TCGM_F_Mini_ScotchR",
	"TCGM_F_Mini_Journalist",
	"TCGM_F_Mini_Marshal",
	"TCGM_F_Mini_Range",
	"TCGM_F_Mini_Competitor",
	
	"TCGM_f_Swimsuit_Flowers",
	"TCGM_f_Swimsuit_Hearts",
	"TCGM_f_Swimsuit_Leafs",
	"TCGM_f_Swimsuit_Maya",
	"TCGM_f_Swimsuit_Poker",
	
	"TCGM_F_WetsuitShort_Blu_C",
	"TCGM_F_WetsuitShort_Gry_C",
	"TCGM_F_WetsuitShort_Grn_C",
	"TCGM_F_WetsuitShort_Pnk_C",
	"TCGM_F_WetsuitShort_Ylw_C",
	"TCGM_F_WetsuitShort_I",
	"TCGM_F_WetsuitShortG_O",
	"TCGM_F_WetsuitShort_O",
	"TCGM_F_WetsuitShort_B",
	
	"ACE_Tripod",
	
	// 82mm Mortar Rounds
	"ACE_1Rnd_82mm_Mo_HE",
	"ACE_1Rnd_82mm_Mo_Illum",
	"ACE_1Rnd_82mm_Mo_Smoke",
	"ACE_1Rnd_82mm_Mo_HE_Guided",
	"ACE_1Rnd_82mm_Mo_HE_LaserGuided",
	
	// VR Suit
	"U_I_Protagonist_VR",
	"U_O_Protagonist_VR",
	"U_B_Protagonist_VR",
	"U_C_Protagonist_VR",
	
	// Viper Suit and Helmet
	"U_O_V_Soldier_Viper_F",
	"U_O_V_Soldier_Viper_hex_F",
	"H_HelmetO_ViperSP_ghex_F",
	"H_HelmetO_ViperSP_hex_F",
	"TCGM_F_Viper_GHex",
	"TCGM_F_Viper_AHex",
	"TCGM_F_Viper_UHex",
	"TCGM_Helmet_Viper_O_UHex",
	
	// Vanila Deployable Bags
	"B_Respawn_Sleeping_bag_blue_F",
	"B_Respawn_Sleeping_bag_brown_F",
	"B_Respawn_TentDome_F",
	"B_Respawn_Sleeping_bag_F",
	"B_Respawn_TentA_F",
	"I_GMG_01_A_weapon_F",
	"O_GMG_01_A_weapon_F",
	"B_GMG_01_A_weapon_F",
	"I_HMG_01_A_weapon_F",
	"B_HMG_01_A_weapon_F",
	"O_HMG_01_A_weapon_F",
	"O_HMG_01_weapon_F",
	"B_HMG_01_weapon_F",
	"I_HMG_01_weapon_F",
	"I_HMG_01_high_weapon_F",
	"O_HMG_01_high_weapon_F",
	"B_HMG_01_high_weapon_F",
	"O_GMG_01_weapon_F",
	"I_GMG_01_weapon_F",
	"B_GMG_01_weapon_F",
	"B_GMG_01_high_weapon_F",
	"I_GMG_01_high_weapon_F",
	"O_GMG_01_high_weapon_F",
	"I_Mortar_01_support_F",
	"B_Mortar_01_support_F",
	"O_Mortar_01_support_F",
	"B_Mortar_01_weapon_F",
	"O_Mortar_01_weapon_F",
	"I_Mortar_01_weapon_F",
	"B_HMG_01_support_F",
	"O_HMG_01_support_F",
	"I_HMG_01_support_F",
	"B_HMG_01_support_high_F",
	"O_HMG_01_support_high_F",
	"I_HMG_01_support_high_F",
	"B_AA_01_weapon_F",
	"O_AA_01_weapon_F",
	"I_AA_01_weapon_F",
	"B_AT_01_weapon_F",
	"O_AT_01_weapon_F",
	"I_AT_01_weapon_F",
	"B_rhsusf_B_BACKPACK",
	"B_Talon_01_backpack_F",
	"B_AssaultPack_Kerry",
	"B_Patrol_Respawn_bag_F",
	"B_Static_Designator_01_weapon_F",
	"O_Static_Designator_02_weapon_F",
	
	//RHS Deployable Bags
	"RHS_Podnos_Bipod_Bag",
	"RHS_Podnos_Gun_Bag",
	"RHS_Kornet_Gun_Bag",
	"RHS_Kornet_Tripod_Bag",
	"RHS_DShkM_Gun_Bag",
	"RHS_DShkM_TripodHigh_Bag",
	"RHS_DShkM_TripodLow_Bag",
	"RHS_Metis_Gun_Bag",
	"RHS_Metis_Tripod_Bag",
	"RHS_AGS30_Tripod_Bag",
	"RHS_AGS30_Gun_Bag",
	"RHS_Kord_Tripod_Bag",
	"RHS_Kord_Gun_Bag",
	"RHS_M2_Gun_Bag",
	"RHS_M2_Tripod_Bag",
	"RHS_M2_MiniTripod_Bag",
	"RHS_Mk19_Gun_Bag",
	"RHS_SPG9_Gun_Bag",
	"RHS_Tow_Gun_Bag",
	"rhs_M252_Gun_Bag",
	"rhs_M252_Bipod_Bag",
	"RHS_Mk19_Tripod_Bag",
	"RHS_NSV_Tripod_Bag",
	"RHS_NSV_Gun_Bag",
	"RHS_SPG9_Tripod_Bag",
	"rhs_Tow_Gun_Bag",
	"rhs_TOW_Tripod_Bag",
	
	// UAVs and IDAP stuffs
	"B_UAV_01_backpack_F",
	"O_UAV_01_backpack_F",
	"I_UAV_01_backpack_F",
	"C_IDAP_UAV_01_backpack_F",
	"B_UAV_06_backpack_F",
	"O_UAV_06_backpack_F",
	"I_UAV_06_backpack_F",
	"C_UAV_06_backpack_F",
	"C_IDAP_UAV_06_antimine_backpack_F",
	"C_IDAP_UAV_06_backpack_F",
	"C_IDAP_UAV_06_medical_backpack_F",
	"I_UAV_06_medical_backpack_F",
	"O_UAV_06_medical_backpack_F",
	"B_UAV_06_medical_backpack_F",
	"C_UAV_06_medical_backpack_F",

	// ROK 2035 Deployable Bags
	"k6_mg_low_bag",
	"k6_mg_high_bag",


	// Russia 2035 Deployable Bags
	"min_rf_torna_flora_Mortar_s",
	"min_rf_torna_flora_Mortar_w",
	"min_rf_torna_flora_HMG_s",
	"min_rf_torna_flora_HMG_w",
	"min_rf_torna_flora_GMG_w",
	"min_rf_torna_flora_AGS_30_w",
	"min_rf_torna_flora_Kord_w",
	"min_rf_torna_flora_Metis_w",
	"min_rf_torna_flora_AGS_30_s",
	"min_rf_torna_flora_Kord_s",
	"min_rf_torna_flora_Metis_s",
		
	// FFAA deployable bags
	"ffaa_lag40_tripode_Bag",
	"ffaa_m2_tripode_Bag",
	"ffaa_milan_tripode_Bag",
	"ffaa_mistral_tripode_Bag",
	"ffaa_spike_tripode_Bag",
	"ffaa_tow_tripode_Bag",
	"ffaa_Tripod_Bag",

	// Blacklisted Magazines
	"R3F_securite_mag",
	"rhsusf_mag_10Rnd_STD_50BMG_mk211",
	"rhsusf_5Rnd_FRAG",
	"rhsusf_5Rnd_HE",
	"rhsusf_8Rnd_FRAG",
	"rhsusf_8Rnd_HE",
	"R3F_10Rnd_127x99_PEI_M107",
	"R3F_7Rnd_127x99_PEI_PGM",
	"ffaa_127x99_he",
	"BPX_UTS15_HE",
	
	
	// mas magazines
	"150Rnd_mas_ger_762x51_Mag",
	"150Rnd_mas_ukl_762x51_Mag",
	"150Rnd_mas_fra_762x51_Mag",
	"150Rnd_mas_ukl_556x45_Drum_Mag_F",
	"150Rnd_mas_ukl_556x45SD_Drum_Mag_F",
	"200Rnd_mas_ger_556x45SD_Drum_Mag_F",
	"200Rnd_mas_ukl_556x45SD_Drum_Mag_F",
	"200Rnd_mas_fra_556x45SD_Drum_Mag_F",
	"200Rnd_mas_ger_556x45_Drum_Mag_F",
	"200Rnd_mas_ukl_556x45_Drum_Mag_F",
	"200Rnd_mas_fra_556x45_Drum_Mag_F",
	"20Rnd_mas_fra_762x51sd_Mag",
	"20Rnd_mas_ukl_762x51sd_Mag",
	"20Rnd_mas_idf_762x51sd_Mag",
	"20Rnd_mas_ger_762x51sd_Mag",
	"20Rnd_mas_fra_762x51_Mag",
	"20Rnd_mas_ger_762x51_Mag",
	"20Rnd_mas_ukl_762x51_Mag",
	"30Rnd_mas_idf_545x39sd_Stanag",
	"30Rnd_mas_idf_556x45sd_Stanag",
	"30Rnd_mas_fra_556x45sd_Stanag",
	"30Rnd_mas_ger_556x45sd_Stanag",
	"30Rnd_mas_ukl_556x45sd_Stanag",
	"30Rnd_mas_ger_556x45_Stanag",
	"30Rnd_mas_fra_556x45_Stanag",
	"30Rnd_mas_ukl_556x45_Stanag",
	"7Rnd_mas_fra_408_Mag",
	"7Rnd_mas_fra_408_APDS_Mag",
	"7Rnd_mas_ger_408_Mag",
	"7Rnd_mas_ger_408_APDS_Mag",
	"7Rnd_mas_ukl_408_Mag",
	"7Rnd_mas_ukl_408_APDS_Mag",
	"30Rnd_mas_idf_9sd_Stanag",
	"30Rnd_mas_ukl_9x21sd_Stanag",
	"40Rnd_46x30SD_mas_ukl_mag",
	"40Rnd_46x30SD_mas_fra_mag",
	"40Rnd_46x30SD_mas_ger_mag",
	"jav_AP_mas_ger",
	"jav_AT_mas_ger",
	"Stinger_mas_ger",

	"rhs_VG40TB",
	
	// AMF Magazines
	"AA12_20rnd_HEMag",
	"AS50HE_mag",
	"Barret25HE_mag",
	"BarretHE_mag",
	"M4m855a1_100mag",
	"M4m855a1d_100mag",
	"M4262_100mag",
	"M4262d_100mag",
	"M4318_100mag",
	"M4318d_100mag",
	"MCRS_14rnd_HEMag",
	"41630m855a1_100mag",
	"41630m855a1d_100mag",
	"41630mk262_100mag",
	"41630mk262d_100mag",
	"41630mk318_100mag",
	"41630mk318d_100mag",	
				
	// Blacklisted Grenades and Explosives
	"I_IR_Grenade",
	"O_IR_Grenade",
		
	// Blacklisted UAV Terminals
	"I_UavTerminal",
	"C_UavTerminal",
	"O_UavTerminal",
	"min_rf_UavTerminal",
	
	// Blacklisted Weapons
	"R3F_LGI_DEM",	
	"UK3CB_BAF_L135A1",
	"arifle_SPAR_03_blk_F",
	"ffaa_armas_hk417A2",
	"R3F_AT4CS",
	"R3F_ERYX",
	"rhs_weap_panzerfaust60",
	"HLC_wp_M134Painless",
	
	"arifle_mas_fra_SPAR_03_blk_F",
	"arifle_mas_fra_SPAR_03_snd_F",
	"arifle_mas_ukl_SPAR_03_blk_F",
	
	"bjc_rhs_m4a1_mc_pmag",
	"bjc_rhs_m4a1_mc_carryhandle_pmag",
	"bjc_rhs_m4a1_wht_pmag",
	"bjc_rhs_m4a1_wht_carryhandle_pmag",
	"SMA_ACRREMAFGblk_N",
	
	"arifle_mas_idf_uzi_F",
	"launch_mas_fra_javelin_F",
	"launch_mas_ukl_javelin_F",
	"launch_mas_fra_Stinger_F",
	"launch_mas_ukl_Stinger_F",
	"launch_mas_idf_Stinger_F",
	"launch_mas_idf_javelin_F",
	"launch_mas_idf_Strela_F",
	"launch_min_rf_titan_short",
	
	"arifle_mas_ukl_mp5_F",
	"arifle_mas_fra_mp7v_F",
	"arifle_mas_ger_mp7v_F",
	"arifle_mas_ukl_mp7v_F",
	"arifle_mas_fra_mp7_F",
	"arifle_mas_ger_mp7_F",
	"arifle_mas_ukl_mp7_F",
	
	"hgun_mas_fra_glock_F",
	"hgun_mas_idf_glock_F",
	"hgun_mas_ukl_P226_F",
	"hlc_pistol_P239_357",
	"hlc_pistol_DL44",
	
	"ej_m468",
	
	// Blacklisted Devices
//	"ACE_Banana",
	"ACE_bodyBag",
	"ACE_SpraypaintBlack",
	"ACE_SpraypaintRed",
	"ACE_SpraypaintGreen",
	"ACE_SpraypaintBlue",
	"item_R3F_SIT_COMDE",
	"HLC_Charm_base",
	"FFAA_cuerda",
	"FIR_Gunbbang",
	"MineDetector",
	"ACE_Sandbag_empty",

	// Contact DLC
	"I_E_GMG_01_A_Weapon_F",
	"I_E_HMG_01_A_Weapon_F",
	"I_E_HMG_01_high_Weapon_F",
	"I_E_HMG_01_Weapon_F",
	"I_E_GMG_01_high_Weapon_F",
	"I_E_GMG_01_Weapon_F",
	"I_E_Mortar_01_support_F",
	"I_E_Mortar_01_Weapon_F",
	"I_E_HMG_01_support_high_F",
	"I_E_HMG_01_support_F",
	"B_W_Static_Designator_01_weapon_F",
	"I_E_UAV_06_backpack_F",
	"I_E_UAV_06_medical_backpack_F",
	"I_E_UAV_01_backpack_F",
	"C_IDAP_UGV_02_Demining_backpack_F",
	"I_UGV_02_Demining_backpack_F",
	"O_UGV_02_Demining_backpack_F",
	"I_E_UGV_02_Demining_backpack_F",
	"B_UGV_02_Demining_backpack_F",
	"I_UGV_02_Science_backpack_F",
	"O_UGV_02_Science_backpack_F",
	"I_E_UGV_02_Science_backpack_F",
	"B_UGV_02_Science_backpack_F",

	// UAV Terminals
	"I_UavTerminal",
	"O_UavTerminal",
	"C_UavTerminal",
	"min_rf_UavTerminal",
	"I_E_UavTerminal",
	
	// CSW Launcher Bags
	"ace_compat_rhs_afrf3_2b14_carry",
	"ace_compat_rhs_afrf3_metis_carry",
	"ace_compat_rhs_afrf3_kornet_carry",
	"ace_compat_rhs_afrf3_ags30_carry",
	"ace_compat_rhs_usf3_tow_carry",
	"ace_compat_rhs_gref3_dshkm_carry",
	"ace_compat_rhs_afrf3_kord_carry",
	"ace_compat_rhs_usf3_m2_carry",
	"ace_compat_rhs_usf3_m252_carry",
	"ace_compat_rhs_usf3_mk19_carry",
	"ace_csw_staticMortarCarry",
	"ace_csw_carryMortarBaseplate",
	"ace_compat_rhs_afrf3_nsv_carry",
	"ace_csw_sag30CarryTripod",
	"ace_csw_spg9CarryTripod",
	"ace_compat_rhs_afrf3_spg9_carry",
	"ace_compat_rhs_afrf3_spg9m_carry",
	"ace_csw_staticAACarry",
	"ace_csw_staticATCarry",
	"ace_csw_staticGMGCarry",
	"ace_csw_staticHMGCarry",
	"ace_csw_kordCarryTripod",
	"ace_csw_kordCarryTripodLow",
	"ace_csw_m220CarryTripod",
	"ace_csw_m3CarryTripod",
	"ace_csw_m3CarryTripodLow",
	"ace_dragon_super",
	"ace_csw_staticM2ShieldCarry",
	
	"sfp_rbs69",
	
	"I_AMF_A_E_B_support_F",
	"O_AMF_A_E_B_support_F",
	"B_AMF_A_E_B_support_F",
	"I_AMF_A_E_B_weapon_F",
	"O_AMF_A_E_B_weapon_F",
	"B_AMF_A_E_B_weapon_F",
	
	"sfp_grsp_weapon_bag",
	"sfp_grsp_support_bag",
	"sfp_grkm84_support_bag",
	"sfp_grkm84_weapon_bag",	
	"sfp_ksp88_weapon_bag",
	"sfp_ksp88_support_bag",
	
	"sfp_rbs17_weapon_bag",
	"sfp_rbs17_support_bag",
	"sfp_rbs55_weapon_bag",
	"sfp_rbs55_support_bag",
	"sfp_rbs56_weapon_bag",
	"sfp_rbs56_support_bag",
	"sfp_rbs70_weapon_bag",
	"sfp_rbs70_support_bag",

	"sfp_kamin_bag",
	"sfp_tent12_bag",
	
	"FirstAidKit",
	"Medikit",
	
	// AMF Weapons
	"Rifle_Base_F",
	"AMF_Samas_F1_01_F",
	"AMF_Samas_F1_01_camo_F",
	"AMF_Famas_valo_01_F",
	"AMF_614_long_01_F",
	"AMF_614_long_ag_01_F",
	"AMF_614_long_VG_01_F",
	"AMF_614_long_HK269_01_F",
	"AMF_614_short_01_F",
	"AMF_614_short_ag_01_F",
	"AMF_614_short_vg_01_F",
	"AMF_714_Long_01_F",
	"AMF_714_short_01_F",
	
	"hlc_rifle_hk53RAS",
	"sfp_kpistm45",
	"sfp_kpistm45b",
	"hlc_smg_9mmar",
	"ej_Thompson",
	"ej_ThompsonTactical",
	"ej_ThompsonTactical2",

	//voice
	"Male01GRE",
	"Male02GRE",
	"Male03GRE",
	"Male04GRE",
	"Male05GRE",
	"Male06GRE",
	"Male01GREVR",
	"Male01PER",
	"Male02PER",
	"Male03PER",
	"Male01PERVR",
	"Male01ENG",
	"Male02ENG",
	"Male03ENG",
	"Male04ENG",
	"Male05ENG",
	"Male06ENG",
	"Male07ENG",
	"Male08ENG",
	"Male09ENG",
	"Male10ENG",
	"Male11ENG",
	"Male12ENG",
	"Male01ENGB",
	"Male02ENGB",
	"Male03ENGB",
	"Male04ENGB",
	"Male05ENGB",
	"Male01ENGVR",
	"Male01CHI",
	"Male02CHI",
	"Male03CHI",
	"Male01FRE",
	"Male02FRE",
	"Male03FRE",
	"Male01ENGFRE",
	"Male02ENGFRE",
	"Male01RUS",
	"Male02RUS",
	"Male03RUS",
	"Male01POL",
	"Male02POL",
	"Male03POL",
	"RHS_Male01RUS",
	"RHS_Male02RUS",
	"RHS_Male03RUS",
	"RHS_Male04RUS",
	"RHS_Male05RUS",
	"RHS_Male01CZ",
	"RHS_Male02CZ",
	"RHS_Male03CZ",
	"RHS_Male04CZ",
	"RHS_Male05CZ",
	"RHS_Female01ENG",

	//Old Man DLC
	"I_HMG_02_high_weapon_F",
	"I_G_HMG_02_high_weapon_F",
	"I_E_HMG_02_high_weapon_F",
	"I_C_HMG_02_high_weapon_F",
	"I_HMG_02_weapon_F",
	"I_G_HMG_02_weapon_F",
	"I_E_HMG_02_weapon_F",
	"I_C_HMG_02_weapon_F",
	
	"I_HMG_02_support_high_F",
	"I_G_HMG_02_support_high_F",
	"I_E_HMG_02_support_high_F",
	"I_C_HMG_02_support_high_F",
	"I_HMG_02_support_F",
	"I_G_HMG_02_support_F",
	"I_E_HMG_02_support_F",
	"I_C_HMG_02_support_F",
	
	//Tarkov Uniforms
	"B6SH118",
	"Blackjack50"
];

blacklist1;